# Generated by Django 5.2 on 2025-04-18 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'school_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assigned',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.IntegerField(blank=True)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='auth_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='auth_group_permissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='auth_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='auth_user_groups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='auth_user_user_permissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_number', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.IntegerField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=45, null=True)),
                ('time_start', models.IntegerField(blank=True, null=True)),
                ('time_end', models.IntegerField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='class_room',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=45, null=True)),
                ('roomid', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'class_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='django_admin_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='django_content_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='django_migrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='django_session',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='final_grade',
            fields=[
                ('letter', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'final_grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='includes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'includes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivesFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recieves_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_number_id', models.IntegerField(blank=True, null=True)),
                ('section_id', models.IntegerField(blank=True, null=True)),
                ('homeroom_id', models.IntegerField(blank=True, null=True)),
                ('math_id', models.IntegerField(blank=True, null=True)),
                ('science_id', models.IntegerField(blank=True, null=True)),
                ('english_id', models.IntegerField(blank=True, null=True)),
                ('social_studies_id', models.IntegerField(blank=True, null=True)),
                ('gym_id', models.IntegerField(blank=True, null=True)),
                ('music_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivesGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.ForeignKey(blank=True, db_column='class_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.class')),
                ('letter', models.ForeignKey(blank=True, db_column='letter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.final_grade')),
                ('section', models.ForeignKey(blank=True, db_column='section', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recievesgrade_section_set', to='school_app.class')),
            ],
            options={
                'db_table': 'recieves_grade',
                'managed': (False,),
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='school_app.school_member')),
                ('street_name', models.CharField(blank=True, max_length=45, null=True)),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('province', models.CharField(blank=True, max_length=45, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.OneToOneField(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='school_app.school_member')),
                ('scheduleid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.OneToOneField(db_column='teacherid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='school_app.school_member')),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='scheduled',
            fields=[
                ('roomid', models.OneToOneField(db_column='roomid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='school_app.class_room')),
            ],
            options={
                'db_table': 'scheduled',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='receivesgrade',
            name='studentid',
            field=models.ForeignKey(blank=True, db_column='studentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.student'),
        ),
        migrations.CreateModel(
            name='educates',
            fields=[
                ('teacherid', models.OneToOneField(db_column='teacherid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='school_app.teacher')),
            ],
            options={
                'db_table': 'educates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='individual_progress_plan',
            fields=[
                ('teacherid', models.OneToOneField(db_column='teacherid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='school_app.teacher')),
                ('goals', models.TextField(blank=True, null=True)),
                ('specified_disability', models.CharField(blank=True, max_length=45, null=True)),
                ('educational_aids', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'individual_progress_plan',
                'managed': False,
            },
        ),
    ]
