# Generated by Django 5.2 on 2025-04-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_school_member_assigned_attendance_auth_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('roomid', models.IntegerField(max_length=45, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=45, null=True)),
                ('room_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'class_room',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='class_room',
        ),
        migrations.AlterModelOptions(
            name='receivesgrade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'schedule', 'verbose_name_plural': 'schedules'},
        ),
    ]
